### ISSUE TITLE
"Could not execute entrypoint stage 'main' due to errors, provided by 'efallingtrees'!"

### ISSUE THREAD

**Issue by Kiznel** [addavriance/EnhancedFallingTrees#1]
**MC Version** 1.20.1
**Loader Version** Quilt 0.26.3
**Mod Version** efallingtrees-0.5.0-1.20+fabric

This errors appears on first launch of a multiplayer server after adding this mod to the 'mods' directory. It doesn't appear on the client/singleplayer version.

```java
[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'efallingtrees'!
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:65) ~[quilt-loader-0.26.3.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[minecraft-1.20.1.i0:0/:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.26.3.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) ~[quilt-loader-0.26.3.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:66) ~[quilt-loader-0.26.3.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_4002
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:321) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:351) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:190) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:176) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.26.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at me.adda.enhanced_falling_trees.fabric.FallingTreesFabric.onInitialize(FallingTreesFabric.java:14) ~[efallingtrees-0.5.0-1.20fabric.i0:0/:?]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:65) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.26.3.jar:?]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4002
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:204) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:176) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.26.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:321) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:351) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:190) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:176) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.26.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at me.adda.enhanced_falling_trees.fabric.FallingTreesFabric.onInitialize(FallingTreesFabric.java:14) ~[efallingtrees-0.5.0-1.20fabric.i0:0/:?]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:65) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.26.3.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.26.3.jar:?]
        ... 12 more```

**Comment by addavriance** [comment]
Hey,

The mod is made for Fabric or Forge, not Quilt. That might be why it isn't working. It's clearly stated for Fabric currently.

**Comment by addavriance** [comment]
Hey,

The mod is made for Fabric, not Quilt. That might be why it isn't working. It's clearly stated for Fabric currently.

**Comment by Kiznel** [comment]
> Hey,
> 
> The mod is made for Fabric, not Quilt. That might be why it isn't working. It's clearly stated for Fabric currently.

Hi,

The mod seems to work fine on Quilt 0.26.3 client. The error only shows on a server.

**Comment by addavriance** [comment]
Although most of the mods on Fabric can work on Quilt, since Quilt is a fork of Fabric, but the keyword is "most". I can't say for sure how the structure of the server part works, but maybe once my mod does not have a Quilt loader, it can't load it. In any case, this will be resolved over time as soon as I add Quilt support.
