### ISSUE TITLE
"java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'efallingtrees'! " Error on server boot

### ISSUE THREAD

**Issue by linkagejr** [addavriance/EnhancedFallingTrees#2]
I'm using:
Fabric loader: 0.16
Minecraft 1.20.1

On a modded server. I attracted the log. When attempting to boot with it, it provides:
"java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'efallingtrees'! 
[latest.log](https://github.com/user-attachments/files/16641559/latest.log)

**Comment by addavriance** [comment]
Can you provide the entire crash log instead of just the basic latest log? I see that there is an exception caused during the particle registry step, but I don't understand why. So far it seems to me that the problem is with the fabric loader version, you need to use a version lower than 0.16. 

For now, I'll try to reproduce this problem myself.

**Comment by linkagejr** [comment]
So when I attempt to try to get a crash log via the server, the server itself freezes (which works fine without it) and it doesn't produce a crash log. I can only kill the server and gather a log. I'm assuming its a fabric version as well. Sorry I wasn't able to get that log.

**Comment by mrafto** [comment]
Same or similar error.

Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.SpriteProvider
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/SpriteProvider

Server completely crashes, no crash log. Looks like the mod is trying to client-sided operations on the server-side. I'll try to resolve the problem myself, will update.

```
[20:25:45] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'efallingtrees' at 'me.adda.enhanced_falling_trees.fabric.FallingTreesFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.7.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.7.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/SpriteProvider
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at me.adda.enhanced_falling_trees.fabric.FallingTreesFabric.onInitialize(FallingTreesFabric.java:14) ~[efallingtrees-0.5.0-1.20+fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.7.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.SpriteProvider
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at me.adda.enhanced_falling_trees.fabric.FallingTreesFabric.onInitialize(FallingTreesFabric.java:14) ~[efallingtrees-0.5.0-1.20+fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.7.jar:?]
	... 6 more
```

**Comment by mrafto** [comment]
If you just make the mod check if its a server and then disable client operations if it is should fix the problem. Very easy fix, can probably make a pull request with the fix tomorrow.

**Comment by addavriance** [comment]
You're right, I forgot that particles should be registered on the client side in the case of Fabric (though I didn't forget about Forge).

I've fixed this and will release it soon in a new version.
